#Build phase
FROM docker.io/node:18-alpine
WORKDIR /usr/app
COPY ./package.json ./
RUN npm install
COPY . .
RUN npm run build

#Run phase
FROM docker.io/node:18-alpine
WORKDIR /usr/app
COPY ./package.json ./
RUN npm install
COPY . .
CMD ["node",  "server.js"]