-- Drop tables
DROP TABLE episodeIV;

-- Activity 2:
-- For Episode IV
CREATE TABLE episodeIV (name STRING, line STRING) 
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' TBLPROPERTIES ("skip.header.line.count"="2");
LOAD DATA LOCAL INPATH '/root/inputs/episode4.txt' INTO TABLE episodeIV;

INSERT OVERWRITE LOCAL DIRECTORY '/root/HiveOutput2'
SELECT COUNT(*) FROM episodeIV WHERE INSTR(line, 'Luke')>0;