services:
    #postgres DB
    postgres:
        image: "postgres:latest"
        environment:
            - POSTGRES_PASSWORD=postgres_password
    #Redis db     
    redis:
        image: 'redis:latest'
        command: [ "redis-server", "--protected-mode", "no" ]
    api:
        build:
            context: ./server
        image: "docker.io/nithya319/complex-api"
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    #worker
    worker:
        build: ./worker
        image: "docker.io/nithya319/complex-worker"
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    #client      
    client:
        build: ./client
        image: "docker.io/nithya319/complex-client"

    #Ngnix
    nginx:
        depends_on:
            - api
            - client
        restart: always
        build:
            context: ./nginx
        ports:
            - '3050:80'
